version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: financial_insights_db
    environment:
      # O main.go aguarda "postgres://user:pass@localhost:5432/financialdb"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: financialdb
    ports:
      - "5432:5432"
    volumes:
      # Volume mapeado para persistir dados mesmo desligando o container
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d financialdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
